### ISSUE TITLE
Roadmap for a color-managed workflow in three.js

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#23614]
## Overview

Summary issue to organize and track progress toward offering a color-managed workflow in three.js. Loosely based on Maya's documentation, I'll define color management as follows:

> Color management involves applying the appropriate transforms to convert between color spaces as needed. These transforms are applied at specific points along the initialization, rendering, and display processes. For example:
> 
> - On input, a transform is applied to convert colors and textures from the color space in which they were saved into the working color space.
> - As you work, colors in the working color space may be converted to/from other color spaces in order to accommodate bit depth and precision considerations.
> - On output to an image or display, an output transform is applied to convert colors appropriately for the image format or browser and device capabilities.

## Roadmap

1. [x] **(1.1)** Add documentation of color management APIs (@donmccurdy)
    - [x] https://github.com/mrdoob/three.js/pull/23430
2. [x] **(1.2)** Loaders identify and convert color spaces correctly (@gkjohnson)
    - [x] https://github.com/mrdoob/three.js/issues/23283
3. [x] **(1.3)** Rename "encoding" properties more precisely as "colorSpace" (@donmccurdy + @Mugen87)
    - [x] `renderer.outputEncoding` → `renderer.outputColorSpace` 
        - https://github.com/mrdoob/three.js/pull/23936
        - https://github.com/mrdoob/three.js/pull/25756
    - [x] `texture.encoding` → `texture.colorSpace`
        - https://github.com/mrdoob/three.js/pull/25771
4. [x] **(1.4)** Change output color space default from Linear-sRGB to sRGB (@donmccurdy)
    - [x] https://github.com/mrdoob/three.js/pull/25783
5. [x] **(1.5)** Convert some inputs automatically from sRGB to Linear-sRGB (@donmccurdy)
    - [x] hexadecimal and CSS inputs: https://github.com/mrdoob/three.js/pull/23392
6. [x] **(1.6)** Change `texture.colorSpace` default to `THREE.NoColorSpace` (e.g. normal maps)
    - https://github.com/mrdoob/three.js/pull/25771
7. [x] **(1.7)** ~~Ensure intermediate frame buffers have sufficient bit depth for their color space.~~ See https://github.com/mrdoob/three.js/issues/23251#issuecomment-1014606909. No changes required.
8. [x] **(1.8)**  Let `CubeTextureLoader` return sRGB cube textures by default.
    - [x] #26162
 9. [x] **(1.9)** Change `renderer.useLegacyLights` default to `false`
    - [x] #26392

_**Timing considerations:** If we are doing (1.3), (1.4), and (1.5), it would cause less disruption to existing code if we can make these changes within the same release. Fewer changes, if any, will be required for end-user code._

## Future

_These changes are more speculative, and may be considered explorative steps toward support for wide-gamut color spaces in WebGPU and SVG renderers._

1. [ ] **(2.1)** Support changing `ColorManagement.workingColorSpace`
2. [ ] **(2.2)** Support color input/output in Display P3 color space
3. [ ] **(3.3)** Support vertex color workflow changes if necessary (`ColorBufferAttribute`?)

_Continued in https://github.com/mrdoob/three.js/issues/26479_.

**Comment by gkjohnson** [comment]
>  (1.2) Loaders identify and convert color spaces correctly (@gkjohnson)

From my perspective this is nearly done. Aside from FBX the most common format loaders and exporters are converted to handle the current three.js color system correctly. The rest I think are less commonly used and / or I don't know a lot about. It would be nice if someone could help with the FBXLoader and example conversion.

**Comment by donmccurdy** [comment]
#23392 (1.5) has been merged, and I'm hoping #23430 (1.1) will also make it into r139. 

At this point we may want to pause for a release or two, and see if there's feedback from users adopting the new `ColorManagement.legacyMode = false` option. I'm inclined to batch the 'breaking' changes together as much as possible. Those include (1.3) and (1.4) above, and — perhaps depending on feedback? — enabling `.legacyMode = false` by default.

**Comment by bhouston** [comment]
> we should consider enabling renderer.physicallyCorrectLights = true by default at some point as well.

That would be amazing!  It was always a hack to make it false, but it was required initially until we settled on it being the right solution: https://github.com/mrdoob/three.js/pull/8260

**Comment by donmccurdy** [comment]
Feedback from the R3F folks (https://github.com/pmndrs/react-three-fiber/issues/2127) has been that switching old demos to `physicallyCorrectLights` is hard, e.g. every light needs `.intensity *= Math.PI` and a considerable reduction in `.decay` to preserve the same look.

What is WebGPURenderer doing in terms of `physicallyCorrectLights`? I can't tell from the code but I think we should at least omit the property there and stick with physically-correct lighting. Users can always reduce `light.decay` if they need more artistic control.

**Comment by drcmda** [comment]
when we switched to physicallyCorrectLights it seemed a change that is too big to just put out there. it didn't seem straight forward to restore projects and demos, everything turned pitch black. two properties (decay and intensity) didn't make it easier to comprehend how to fix it. when three makes it the default i think it should first educate people first how to use it properly, similar to colormanagement.legacy=false and the new article explaining everything.

as for color management, react+three + eco system uses it by default now. i have already updated most sandboxes and everything works great. i love being able to omit the occasional convertSRGBToLinear and everything behaves much more consistent.

**Comment by mrdoob** [comment]
What we could do is to make `WebGPURenderer` physically correct and be the only mode.

If a developer uses `WebGPURenderer` and wants to use `WebGLRenderer` as fallback, they'd have to make sure they're setting `physicallyCorrectLights = true` in `WebGLRenderer`.

However, I do not know how to change the lights `decay` to a physically correct value by default without breaking things.

**Comment by donmccurdy** [comment]
I don't feel strongly on whether the `decay` default really needs to change. It's true that it's only physically correct with a value of decay=2, but given all the other constraints of lighting in WebGL that's not a hill I'd choose to die on. And certainly there's no "one size fits all" upgrade path to get people there.

**Comment by Mugen87** [comment]
I'm glad this discussion came up^^. I have not added `physicallyCorrectLights` on purpose when filing the initial version of `WebGPURenderer`.  https://github.com/mrdoob/three.js/issues/23614#issuecomment-1093415286 sounds good to me.

**Comment by sunag** [comment]
> What we could do is to make WebGPURenderer physically correct and be the only mode.

@mrdoob @Mugen87  I agree so much that I was doing this ^^ https://github.com/mrdoob/three.js/pull/23872

**Comment by mrdoob** [comment]
> Perhaps we could change the `decay` default only under `physicallyCorrectLights` somehow; I don't think most users enable that setting so a breaking change _in that mode_ might not be so bad, and e.g. glTF files containing lights will already set decay=2.

Hmmm, I think I'm willing to try changing the default to 2 (this month maybe) and see what happens...

**Comment by donmccurdy** [comment]
One more for the list – GammaCorrectionShader probably should be renamed to match up with the successor to `renderer.outputEncoding`, currently proposed to be `renderer.outputColorSpace`. Generally we should avoid references to 'gamma' in color management APIs.

For example:

```js
composer.addPass( new ShaderPass( ColorSpaceTransformShader ) );
```

Other ideas:

- OutputTransformShader
- OutputColorSpaceShader
- DisplayTransformShader

I'm not sure how to provide configuration options on a Shader object, but in current usage this would be Linear-sRGB to sRGB (the same as GammaCorrectionShader).

**Comment by Mugen87** [comment]
`OutputColorSpaceShader` probably fits best to `WebGLRenderer.outputColorSpace`.

**Comment by Mugen87** [comment]
BTW: I wonder if we could avoid the `output*` prefix. It comes from a time when `gammaInput` and `gammaOutput` were in place. Any objections against the simplified/shortened `WebGLRenderer.colorSpace`?

**Comment by donmccurdy** [comment]
I'm happy with OutputColorSpaceShader if @WestLangley approves. 👍

`WebGLRenderer.colorSpace` might be confusing. The working color space, Linear-sRGB, is at least as relevant to WebGLRenderer as the output color space, sRGB, even if the former is not customizable.

It's also helpful to look at how desktop software like Blender and Maya (both using OpenColorIO) refer to these concepts:

- https://docs.blender.org/manual/en/latest/render/color_management.html#settings
- https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/Maya-Customizing/files/GUID-2D9BBB9D-49F0-44C6-8BFF-B237FD8ED746-htm.html
- https://opencolorio.readthedocs.io/en/latest/guides/authoring/displays_views.html#active-displays

The term "display" is usually involved in describing our equivalent of output color space, whereas "view" and "look" transforms refer to tone mapping. Not a perfect analogy though – desktop software can render more directly to the display, but we're constrained to writing to a Canvas (implicitly sRGB), regardless of what the final display might be. Or the result might be a file rather than a display of course. Perhaps "output" is better than "display" in our context, for these reasons reason.

**Comment by WestLangley** [comment]
Maybe remove `GammaCorrectionShader` and add `ColorSpaceShader`, while retaining the nomenclature `renderer.outputColorSpace`.

//

The thing that is confusing, IMO, is something I mentioned [previously](https://github.com/mrdoob/three.js/issues/18942#issuecomment-613221973). The terminology has changed,  but the issue is the same: when rendering to a render target, do you honor the renderer's settings -- or the render target's texture settings?

**Comment by LeviPesin** [comment]
> when rendering to a render target, do you honor the renderer's settings -- or the render target's texture settings?

Maybe `.outputEncoding` should be understood as just the encoding of the "default" render target - the display?

**Comment by donmccurdy** [comment]
> Maybe remove GammaCorrectionShader and add ColorSpaceShader, while retaining the nomenclature renderer.outputColorSpace.

This is also fine with me. Is there a way for Shader objects to take configuration parameters? If not, we just need to be aware that the generically-named ColorSpaceShader will _only_ do Linear-sRGB to sRGB conversions for the moment.

> > when rendering to a render target, do you honor the renderer's settings -- or the render target's texture settings?
> 
> Maybe .outputEncoding should be understood as just the encoding of the "default" render target - the display?

So the color space of a render target used throughout a post-processing chain should be decoupled from the output color space written to a Canvas. I can't quite tell how this works today – it looks like neither the renderer's nor the render target's encoding is determining the output-to-canvas color space (when post-processing uses Linear-sRGB throughout the internal chain), we instead specify an explicit GammaCorrectionShader?

**Comment by LeviPesin** [comment]
I mean that in terms of encoding, no render target (i.e. `null`) would be equivalent to a render target with encoding `renderer.outputEncoding`. I think that with post-processing it should look like this:

renderer renders scene in LinearEncoding - it applies post-processing effects that are working in linear color space - renderer converts the output to the encoding specified by the encoding of the render target - it applies post-processing effects that are working in output color space

**Comment by donmccurdy** [comment]
Can we deprecate (or just avoid) GammaCorrectionShader in that case? So output to the correct color space is not a separate pass in post-processing. I could — for example — make my last pass a DitherPass applied to linear colors, then write 8-bit sRGB output in the same pass.

**Comment by LeviPesin** [comment]
With what I proposed the renderer (and not the passes) will authomatically convert the output to the correct space and then yes, GammaCorrectionShader is not needed at all.

**Comment by gkjohnson** [comment]
> The thing that is confusing, IMO, is something I mentioned previously. The terminology has changed, but the issue is the same: when rendering to a render target, do you honor the renderer's settings -- or the render target's texture settings?

I far prefer the current model with color spaces set on the targets themselves and don't find it confusing. Though I agree that the naming might be confusing. Perhaps the current "outputEncoding" field on the renderer could be renamed something like "canvasColorSpace" to disambiguate.

**Comment by Mugen87** [comment]
> when rendering to a render target, do you honor the renderer's settings -- or the render target's texture settings?

TBH, I would not start to bring up this controversial topic in this issue. We should focus on the scope defined in the initial post of @donmccurdy. That's what the engine needs to change in order to implement a color-manageed workflow.

**Comment by Mugen87** [comment]
> I far prefer the current model with color spaces set on the targets themselves and don't find it confusing.

Me too. TBH, I don't think the way how the color space is evaluated from the renderer or render target is not critical to solve this issue. With the current model in place, the engine can implement a color-managed workflow by solving the tasks mentioned in the first post of @donmccurdy.

**Comment by donmccurdy** [comment]
I think the color management workflow with render targets and post-processing does block #23937. Honestly I don't feel like I understand the currently model — it does confuse me — but I'll follow up in #23937 instead, to keep this thread. If any change is needed we can just come back and add it to the checklist at the top of this roadmap.

**Comment by donmccurdy** [comment]
^to my last comment — I don't think we need to deal with that right now. It might be that we can carve out a special case for "unlit" scenes, but I'm not even sure what the advantages would be, so let's not try to make a special case without clear use cases and user feedback.

***

**Update** — Safari is adding support for Display P3 wide gamut color space in WebGL:

https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#Web%20Apps

Chrome has announced the same, but I haven't found a way to test that yet.

**Comment by mrdoob** [comment]
Here's an additional resource:

https://ccameron-chromium.github.io/webgl-examples/p3.html

**Comment by mrdoob** [comment]
Hmm...

Is there an API to know if the user's display is `srgb` or `p3`?

/cc @ccameron-chromium

**Comment by mrdoob** [comment]
As proposed "offline" right now I'm thinking we want to set `renderer.outputColorSpace` to `null` by default and let the renderer automatically pick the correct color space depending on the user's display.

But I'm not sure if there's an API to know if the user's display color space is `srgb` or `p3`?

And if we did that... Would this approach work well for when we get HDR support in WebGL?

/cc @ccameron-chromium

**Comment by gkjohnson** [comment]
> But I'm not sure if there's an API to know if the user's display color space is `srgb` or `p3`?

Looks like you can use the [color-gamut media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut) and the [window.macheMedia function](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia):

```js
const isP3ColorSpace = window.matchMedia( '(color-gamut: p3)' ).matches;
```

**Comment by donmccurdy** [comment]
Can check support for both the P3 gamut on the display (above should work), and `gl.drawingBufferColorSpace`. Comparing Safari vs. Safari Technical Preview on any recent macOS laptop display, for example.

> As proposed "offline" right now I'm thinking we want to set renderer.outputColorSpace to null by default and let the renderer automatically pick the correct color space depending on the user's display.

I think the difficult part here is going to be adapting our tone mapping transforms to the P3 gamut... The [Blender Filmic](https://github.com/sobotka/filmic-blender) tone map is the best (and only) option I've found, possibly preferable to our current tone mappings even for sRGB. But simplifying it from a stack of LUTs and other operations ... I'm not sure how to do that yet. Related work in https://github.com/donmccurdy/three-filmic.

> And if we did that... Would this approach work well for when we get HDR support in WebGL?

We probably shouldn't enable HDR without the user specifying. It's difficult to integrate HDR with the rest of a webpage well (also see: ["Instagram is littered with bright-as-h*** HDR videos"](https://www.theverge.com/23529794/instagram-apple-iphone-hdr-video-brightness-samsung-annoying)), I think that's a decision that authors should make intentionally.

**Comment by donmccurdy** [comment]
Possibly a question for @ccameron-chromium ... does `gl.unpackColorSpace` apply gamut mapping, or clipping, when converting from display-p3 to srgb?

**Comment by donmccurdy** [comment]
> we want to set renderer.outputColorSpace to null by default and let the renderer automatically pick...

This would require ColorManagement.enabled=true. Without it fog, background, and clear color must be set in the output color space, so the user needs to be aware of the choice.

**Comment by ccameron-chromium** [comment]
gl.unpackColorSpace uses relative colormetric intent. If the target texture format is floating-point, then the resulting colors may be outside of the [0, 1] interval. If the texture format is unorm, then the resulting colors will be clamped to [0, 1]. It may be that, due to bugs, some content is clamped even when the target texture format is floating-point (if they exist, file a bug and it'll get fixed).

The color space and the pixel format of the drawing buffer are independent. There is a proposal [here](https://github.com/KhronosGroup/WebGL/pull/3222) to add a drawingBufferStorage function which will allow specifying float16 as the drawing buffer format. When using floating point drawing buffers, values outside of the [0, 1] interval can specify any color gamut (and brightness).

There is also [this](https://github.com/w3c/ColorWeb-CG/blob/main/hdr_html_canvas_element.md) HDR canvas element proposal which will introduce the ability to query the precise color volume of the output screen.

With respect to HDR, that same proposal allows querying the precise HDR headroom of the output device. In general I have found that HLG and PQ based content suffer the problem of uncontrollable brightness mentioned above. [Gainmap based approaches](https://www.imaging.org/site/IST/IST/Conferences/EI/EI2023/Program.aspx?ProgramCCO=2) tend to do much better at being controlled (both on the artistic and display end), but unfortunately are currently limited to still images.

**Comment by donmccurdy** [comment]
I see, thanks @ccameron-chromium! Unless/until a proposal like `gl.drawingBufferStorage` is implemented, should we assume the drawing buffer is RGBA8 for both srgb and display-p3 colorspaces?

**Comment by ccameron-chromium** [comment]
Correct, until `drawingBufferStorage` is implemented, it is safe to assume that the drawing buffer is RGBA8 or RGB8 for all color spaces.

**Comment by donmccurdy** [comment]
@mrdoob @WestLangley @Mugen87 — I would be interested in getting tasks **1.3, 1.4, and 1.6** all completed together in an upcoming release. We should do that before trying to complete Display P3 support. Do you think r152 is a reasonable target for this work? I'm willing to make those changes, but it will require some large PRs.

**Comment by Mugen87** [comment]
I definitely support this. 1.3 and 1.6 is something that can be done at any time, IMO. 1.4 is a breaking change that requires more attention. So I would do this last (meaning after completing 1.3 and 1.6) since the other changes _could_ go in production without changing the default color space.

Since you want to make these changes I close https://github.com/mrdoob/three.js/pull/23936 (it has many merge conflicts anyway),

**Comment by donmccurdy** [comment]
My hope is that these are best done together, we reduce the migration pain if we can rename the property and change its default at the same time. Do you have any particular concern about changing the default? Or more a general concern that issues might come up?

I'll start on this just after the r151 release, if that's OK.

**Comment by Mugen87** [comment]
Renaming properties is an easy migration task that usually does not require further input from our side.

However, when a default value changes, things are a bit different. Some users just restore the value others want to use the new (and potentially better/more correct) default. In context of color space conversion users will need more input to achieve a sRGB workflow. IMO, this change is somewhat in need of explanation. My hope is that the documentation will cover most issues but I expect a more support intensive time frame after the change^^.

**Comment by donmccurdy** [comment]
I understand we aren't doing semver, but I believe we do still want to not have more breaking changes than necessary. Agreed that changing the default will require more support and explanation than renaming a property, this is part of the motivation for [dedicated color management documentation](https://threejs.org/docs/#manual/en/introduction/Color-management). If not r152, is there another time you would prefer to do the change in default value? Could we hold off the property renaming until that time instead, so it's all still one release?

**Comment by Mugen87** [comment]
Sorry if my comments were misleading. I don't want to defer the change to a later point. It's indeed best if we bundle everything in on release. Ideally `r152`. I just would change the default color space in a separate PR so it's easier to detect breakage.

Changing the default color space as suggested is the right thing and it's good if we finally getting it over with^^. I'm just fearing a bit the impact of this change so I hope it won't be too bumpy for users.

**Comment by donmccurdy** [comment]
A question, perhaps relevant to @WestLangley @bhouston and @Mugen87 — we intend to change the default value of `renderer.outputColorSpace` to SRGBColorSpace in r152. With the three.js post-processing pipeline, users will need to override that to LinearSRGBColorSpace, then add a "GammaCorrectionShader" to their effect stack. The third-party [`postprocessing`](https://github.com/pmndrs/postprocessing) module handles this more easily — WebGLRenderer's output encoding is applied automatically at the end of the effect stack (or as configured elsewhere), without further input from the user. Do we:

- (A) keep post-processing as-is for r152, and require users to opt out of `outputColorSpace = SRGBColorSpace` if they're using the built-in post-processing
- (B) make deeper changes to post-processing as part of r152
- (C) defer the `outputColorSpace = SRGBColorSpace` change until a later release, only renaming properties (encoding -> colorSpace, outputEncoding -> outputColorSpace) in r152

I'm leaning toward (A) or (C); I don't personally have bandwidth to make more post-processing changes before r152.

**Comment by Mugen87** [comment]
Yes, let's go for A and ensure all post processing examples set `LinearSRGBColorSpace`.

**Comment by WestLangley** [comment]
I would also explicitly set `renderer.outputColorSpace` in every example. That way, users have a consistent pattern to follow.

**Comment by donmccurdy** [comment]
Ok, let's go with (A), thanks!

***

@ccameron-chromium another question, if you don't mind! Do you know whether anything like...

```js
gl.drawingBufferColorSpace = 'srgb-linear' | `p3-linear` | `acescg`
``` 

...is being considered? I'm imagining this would allow three.js to write to the drawing buffer in a linear color space (preferably with greater than RGBA8 precision), with the *browser* applying the EOTF before display.

Currently we have the option of applying the EOTF in a render target (which is costly), or at the end of each fragment shader during initial rendering (which is incorrect for transparent or alpha blended objects).

**Comment by LeviPesin** [comment]
Maybe we should also turn ColorManagment enabled by default in r152 to make the migration to sRGB easier?

**Comment by donmccurdy** [comment]
That would be my preference personally — `THREE.ColorManagement.enabled = true` is enough to handle many of the migrations in https://github.com/mrdoob/three.js/pull/25783.  I believe it's a good way to achieve what @mrdoob describes in https://twitter.com/mrdoob/status/1273743531551551488, creating a workflow consistent with CSS and HTML.

But I don't want to step on toes here: if others are not comfortable with it at this point, that is OK. 😇

**Comment by Mugen87** [comment]
I'm fine with enabling `THREE.ColorManagement.enabled`, too. At this point, it makes sense to integrate this change into `r152`, too.

@donmccurdy Would you prefer to include this change in https://github.com/mrdoob/three.js/pull/25783 or in a different PR?

**Comment by donmccurdy** [comment]
OK, let's update `THREE.ColorManagement.enabled` in an additional PR. I'll be out for a few days, and back on April 14. The remaining changes for r152 will be:

1. Update documentation
2. Update THREE.ColorManagement.enabled default
3. Update remaining examples to set `outputColorSpace` explicitly

**Comment by LeviPesin** [comment]
I think after 2 we wouldn't need to have ColorManagement explicitly enabled like with outputColorSpace -- because ColorManagement feels like an internal thing. So just nothing with ColorManagement in already updated examples and explicit opt-out in others (but outputColorSpace is specified in every example).

**Comment by Mugen87** [comment]
> Update remaining examples to set outputColorSpace explicitly

In general, I'm not a fan of explicitly setting default values since this patterns ends up in verbose code. So I vote to only define `LinearSRGBColorSpace` (and later `THREE.ColorManagement.enabled = false`) where it is actually required.

**Comment by donmccurdy** [comment]
Remaining work:

1. Write migration guide
2. Enable THREE.ColorManagement on remaining 118 examples, where appropriate
3. Enable renderer.outputColorSpace = SRGBColorSpace on remaining 56 examples, where appropriate

I believe (1) is necessary for r152, where (2) and (3) can be completed on a best-effort basis before or after the release.

I'll work on (1) next.

**Comment by Mugen87** [comment]
`r152` will be released next week and publish the many important color management related changes. At this point thanks to @donmccurdy for pushing this topic so far! 

Since this release potentially needs more explanation, I wonder if it's best to write a topic at the forum similar when we removed `THREE.Geometry` and `examples/js`.

https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401
https://discourse.threejs.org/t/the-examples-js-directory-will-be-removed-with-r148/45349

My impression is the community met both topics with positive response since they allowed users to ask related questions without filing new topics or issues. The structure of the topics (consequences of the change, motivation, migration tasks and a roadmap) also provide a compact overview since most users do not follow the entire discussion at GitHub.

I think it's best to write a similar announcement for next week as an addition to the existing migration guide.

**Comment by donmccurdy** [comment]
Thanks @Mugen87, that's a great idea. I'll plan to post something on the forum early next week, and perhaps we link there from the migration guide.

**Comment by Mugen87** [comment]
Awesome topic! I've pinned it globally for a month so it should be clearly visible for all forum users.

**Comment by mrdoob** [comment]
Amazing @donmccurdy! 🙏🙏🙏

Nit:

> I'm still using renderer.outputEncoding = LinearEncoding (default)

How about "(previous default)" instead?

**Comment by donmccurdy** [comment]
Done! ✅

**Comment by mad-wizard** [comment]
@donmccurdy Is there any ETA on P3 color support? I've had to abandon three.js as a solution because color accuracy for our application is mission-critical and we could not get accurate colors.

Would love to re-integrate three but this is holding us back.

Would be willing to assist if required.

Thank you.

**Comment by donmccurdy** [comment]
Hi @mad-wizard!

While I could be misunderstanding the issues you've encountered, I expect that a Display P3 workflow can solve "color accuracy" problems by itself if — and only if — you're using a fully unlit (no lighting) scene. Is that the case here?

In a lit scene, it's more likely that image formation (tone mapping, exposure, lighting, etc.) are the relevant concerns. If you aren't using tone mapping yet, then it's much too early in the image formation process to be worried about Display P3. 🙂

I believe it would also be fair to say that our current tone mapping options could be improved... if this sounds like it would be of interest, would you mind starting a new issue on the color accuracy problems you're facing? I'd also be interested in whether you've found alternatives to three.js that solve the problem better, or whether the problem remains completely unsolved  for now.

P.S. It's a deeper dive, but @elalish's writing on [glTF Color Accuracy](https://modelviewer.dev/examples/color.html) may provide helpful background.

**Comment by mad-wizard** [comment]
> Hi @mad-wizard!
> 
> While I could be misunderstanding the issues you've encountered, I expect that a Display P3 workflow can solve "color accuracy" problems by itself if — and only if — you're using a fully unlit (no lighting) scene. For example, photogrammetry or baked lights. Is that the case here?
> 
> In a lit scene, it's more likely that image formation (tone mapping, exposure, lighting, etc.) are the relevant concerns. If you aren't using tone mapping yet, then it's much too early in the image formation process to be worried about Display P3. 🙂
> 
> I believe it would also be fair to say that our current tone mapping options could be improved... if this sounds like it would be of interest, would you mind starting a new issue on the color accuracy problems you're facing? I'd also be interested in whether you've found alternatives to three.js that solve the problem better, or whether the problem remains completely unsolved for now.
> 
> P.S. It's a deeper dive, but @elalish's writing on [glTF Color Accuracy](https://modelviewer.dev/examples/color.html) may provide helpful background.

Thanks for the response!

Yes I am using a texture rendered on a plane with an unlit material (MeshBasic).

I have tried many encoding and color space changes and have isolated the problem; images taken with modern iPhones use the P3 color profile which has a wider gamut than sRGB. When these images are rendered in three.js they appear washed out.

Here is an example of a P3 image. https://goldeneye.nyc3.cdn.digitaloceanspaces.com/woman.png

 I tried downloading the repo and replacing the texture of the crate in one of the examples, that should be a way for you to easily reproduce the issue.

Since we are making a photo editing app, color quality is mission critical so we were on the verge of abandoning three.js, then this morning I was able to find a work-around where we convert the p3 profile to srgb manually and then use the processed texture in three.js this is not an ideal workaround.

We want to use three.js to implement 3D effects and more advanced features than other photo editing apps.

On an unrelated side-note, do you happen to have any idea on how we could implement photo filters using three.js for this type of app?

Best

Callan

**Comment by gkjohnson** [comment]
> I have tried many encoding and color space changes and have isolated the problem; images taken with modern iPhones use the P3 color profile which has a wider gamut than sRGB.
> ...
> Here is an example of a P3 image. https://goldeneye.nyc3.cdn.digitaloceanspaces.com/woman.png

Independent of supporting the Color Space we need a way of determining what color space is used by a loaded texture. Currently there's no way to determine the color space of an image even if it's correctly embedded (see #21336). And even then when I use image magick to inspect the embedded color space of the image provided it says it's `sRGB`. I'm not sure what the expected approach is for working with new color spaces in WebGL is. As Don mentioned I think this requires making a different issue to discuss.

> On an unrelated side-note, do you happen to have any idea on how we could implement photo filters using three.js for this type of app?

In the interest of keeping issues on topic - you can ask questions at the forum: https://discourse.threejs.org/

**Comment by donmccurdy** [comment]
> And even then when I use image magick to inspect the embedded color space of the image provided it says it's sRGB...

Color space information embedded in PNG or JPEG images is very unreliable, unfortunately. The ICC Profile appears to have the correct information.

I'm viewing this as a web platform issue – as things stand, we can't do it automatically. Perhaps it should be escalated to a W3C working group. In the meantime, and for the foreseeable future, users must identify the color space of their textures with `texture.colorSpace`.

Support for rendering lit scenes in wide color gamuts will be difficult. Support for rendering unlit scenes, much less so. But I'm unsure if we want to attempt one without the other.

Perhaps this issue can now be closed, and another opened to discuss support for wide-gamut color spaces in three.js? This thread has probably covered enough territory already. 😅

**Comment by mad-wizard** [comment]
I can share some ruby code I am using to convert the image from P3 to SRGB. It uses mini-magick:

```ruby
def convert_to_srgb!
    unique_filename = "#{original.filename}-#{SecureRandom.uuid}"
    download_path = Rails.root.join('tmp', unique_filename)
  
    File.open(download_path, 'wb') { |file| file.write(original.download) }
  
    image = MiniMagick::Image.open(download_path)
    color_profile = image["%[profile:icc]"]
  
    unless color_profile.include?("Display P3")
      File.delete(download_path) if File.exist?(download_path)
      return
    end
  
    image.combine_options do |b|
      b.profile("#{Rails.root}/colors/P3.icc")
      b.profile("#{Rails.root}/colors/sRGB.icc")
    end
  
    original.attach(io: File.open(image.path), filename: original.filename.to_s, content_type: original.content_type)
    File.delete(download_path) if File.exist?(download_path)
  end 
```

**Comment by donmccurdy** [comment]
To be continued in https://github.com/mrdoob/three.js/issues/26479.

**Comment by gkjohnson** [comment]
> The ICC Profile appears to have the correct information.

Ha how nice that they keep two out of sync fields with color space information 😅 

```
magick identify -verbose woman.png

    ...
    Colorspace: sRGB
    ...
    icc:copyright: Copyright Apple Inc., 2022
    icc:description: Display P3
    ...
```
