### ISSUE TITLE
Cleanup + document all missing Constancts

### ISSUE THREAD

**Issue by gero3** [mrdoob/three.js#24418]
**Is your feature request related to a problem? Please describe.**

Incorrect documentation can make it difficult to use Three.js.

**Describe the solution you'd like**

Correct Documentation would be helpful for this.

**Additional context**
These are all the constants in [constants.js](https://github.com/mrdoob/three.js/blob/dev/src/constants.js) and if they have documentation.
- [x] REVISION
- [x] MOUSE = { LEFT: 0, MIDDLE: 1, RIGHT: 2, ROTATE: 0, DOLLY: 1, PAN: 2 }; #24423
- [x] TOUCH = { ROTATE: 0, PAN: 1, DOLLY_PAN: 2, DOLLY_ROTATE: 3 }; #24422
- [x] CullFaceNone
- [x] CullFaceBack
- [x] CullFaceFront
- [x] CullFaceFrontBack
- [x] BasicShadowMap
- [x] PCFShadowMap
- [x] PCFSoftShadowMap
- [x] VSMShadowMap
- [x] FrontSide
- [x] BackSide
- [x] DoubleSide
- [x] FlatShading #24424
- [x] SmoothShading #24424
- [x] NoBlending
- [x] NormalBlending
- [x] AdditiveBlending
- [x] SubtractiveBlending
- [x] MultiplyBlending
- [x] CustomBlending
- [x] AddEquation
- [x] SubtractEquation
- [x] ReverseSubtractEquation
- [x] MinEquation
- [x] MaxEquation
- [x] ZeroFactor
- [x] OneFactor
- [x] SrcColorFactor
- [x] OneMinusSrcColorFactor
- [x] SrcAlphaFactor
- [x] OneMinusSrcAlphaFactor
- [x] DstAlphaFactor
- [x] OneMinusDstAlphaFactor
- [x] DstColorFactor
- [x] OneMinusDstColorFactor
- [x] SrcAlphaSaturateFactor
- [x] NeverDepth
- [x] AlwaysDepth
- [x] LessDepth
- [x] LessEqualDepth
- [x] EqualDepth
- [x] GreaterEqualDepth
- [x] GreaterDepth
- [x] NotEqualDepth
- [x] MultiplyOperation
- [x] MixOperation
- [x] AddOperation
- [x] NoToneMapping
- [x] LinearToneMapping
- [x] ReinhardToneMapping
- [x] CineonToneMapping
- [x] ACESFilmicToneMapping
- [x] CustomToneMapping #24419
- [x] UVMapping
- [x] CubeReflectionMapping
- [x] CubeRefractionMapping
- [x] EquirectangularReflectionMapping
- [x] EquirectangularRefractionMapping
- [x] CubeUVReflectionMapping
- [x] RepeatWrapping
- [x] ClampToEdgeWrapping
- [x] MirroredRepeatWrapping
- [x] NearestFilter
- [x] NearestMipmapNearestFilter
- [x] NearestMipMapNearestFilter
- [x] NearestMipmapLinearFilter
- [x] NearestMipMapLinearFilter
- [x] LinearFilter
- [x] LinearMipmapNearestFilter
- [x] LinearMipMapNearestFilter
- [x] LinearMipmapLinearFilter
- [x] LinearMipMapLinearFilter
- [x] UnsignedByteType
- [x] ByteType
- [x] ShortType
- [x] UnsignedShortType
- [x] IntType
- [x] UnsignedIntType
- [x] FloatType
- [x] HalfFloatType
- [x] UnsignedShort4444Type
- [x] UnsignedShort5551Type
- [x] UnsignedInt248Type
- [x] AlphaFormat
- [x] RGBFormat #24421 #24426
- [x] RGBAFormat
- [x] LuminanceFormat
- [x] LuminanceAlphaFormat
- [x] DepthFormat
- [x] DepthStencilFormat
- [x] RedFormat
- [x] RedIntegerFormat
- [x] RGFormat
- [x] RGIntegerFormat
- [x] RGBAIntegerFormat
- [x] RGB_S3TC_DXT1_Format
- [x] RGBA_S3TC_DXT1_Format
- [x] RGBA_S3TC_DXT3_Format
- [x] RGBA_S3TC_DXT5_Format
- [x] RGB_PVRTC_4BPPV1_Format
- [x] RGB_PVRTC_2BPPV1_Format
- [x] RGBA_PVRTC_4BPPV1_Format
- [x] RGBA_PVRTC_2BPPV1_Format
- [x] RGB_ETC1_Format
- [x] RGB_ETC2_Format
- [x] RGBA_ETC2_EAC_Format
- [x] RGBA_ASTC_4x4_Format
- [x] RGBA_ASTC_5x4_Format
- [x] RGBA_ASTC_5x5_Format
- [x] RGBA_ASTC_6x5_Format
- [x] RGBA_ASTC_6x6_Format
- [x] RGBA_ASTC_8x5_Format
- [x] RGBA_ASTC_8x6_Format
- [x] RGBA_ASTC_8x8_Format
- [x] RGBA_ASTC_10x5_Format
- [x] RGBA_ASTC_10x6_Format
- [x] RGBA_ASTC_10x8_Format
- [x] RGBA_ASTC_10x10_Format
- [x] RGBA_ASTC_12x10_Format
- [x] RGBA_ASTC_12x12_Format
- [x] RGBA_BPTC_Format #24427
- [x] LoopOnce
- [x] LoopRepeat
- [x] LoopPingPong
- [x] InterpolateDiscrete
- [x] InterpolateLinear
- [x] InterpolateSmooth
- [x] ZeroCurvatureEnding
- [x] ZeroSlopeEnding
- [x] WrapAroundEnding
- [x] NormalAnimationBlendMode #24428
- [x] AdditiveAnimationBlendMode #24428
- [x] TrianglesDrawMode #24429
- [x] TriangleStripDrawMode #24429
- [x] TriangleFanDrawMode #24429
- [x] LinearEncoding
- [x] sRGBEncoding
- [x] BasicDepthPacking
- [x] RGBADepthPacking
- [x] TangentSpaceNormalMap #24430
- [x] ObjectSpaceNormalMap #24430
- [x] NoColorSpace #24423
- [x] SRGBColorSpace 
- [x] LinearSRGBColorSpace
- [x] ZeroStencilOp
- [x] KeepStencilOp
- [x] ReplaceStencilOp
- [x] IncrementStencilOp
- [x] DecrementStencilOp
- [x] IncrementWrapStencilOp
- [x] DecrementWrapStencilOp
- [x] InvertStencilOp
- [x] NeverStencilFunc
- [x] LessStencilFunc
- [x] EqualStencilFunc
- [x] LessEqualStencilFunc
- [x] GreaterStencilFunc
- [x] NotEqualStencilFunc
- [x] GreaterEqualStencilFunc
- [x] AlwaysStencilFunc
- [x] StaticDrawUsage
- [x] DynamicDrawUsage
- [x] StreamDrawUsage
- [x] StaticReadUsage
- [x] DynamicReadUsage
- [x] StreamReadUsage
- [x] StaticCopyUsage
- [x] DynamicCopyUsage
- [x] StreamCopyUsage
- [x] GLSL1 #24432
- [x] GLSL3 #24432
- [x] _SRGBAFormat

**Comment by gero3** [comment]
I've added a PR for each missing constant. Except for _SRGBAFormat which seems to be an internal constant.

So if each PR is added then this can  be closed.
