### ISSUE TITLE
Documentation Improvement Project

### ISSUE THREAD

**Issue by gregtatum** [mrdoob/three.js#5411]
If you are interested in helping with the documentation please direct your efforts here. This issue will manage and coordinate the various efforts. If you are interested in helping out with something specific leave a comment and I will add your name to the list.

Materials
- [ ] Document what flags need changed when changing properties @TatumCreative
- [ ] MeshNormalMaterial smoothing default incorrect @TatumCreative
- [ ] MeshDepthMaterial.morphTargets not listed @TatumCreative

Extras / Renderers / Plugins
- [ ] http://threejs.org/docs/#Reference/Extras.Renderers.Plugins/DepthPassPlugin
## General Improvements
- [ ] Consolidate information into docs @caseygrun #5410
- [ ] Link to pages in the http://threejs.org/examples/ within the documentation #5405 @Brenden-Morales
- [ ] Issues with mobile layout #5482
- [ ] Document THREE.Group()
## Existing Issues
- [ ] Raycaster #5365 @caseygrun 
- [ ] Euler/Quaternion #5187 @caseygrun 
- [ ] MeshFaceMaterial #4645
- [ ] Documentation does not include inherited methods #4557
- [ ] CSS3DRenderer #3716
# Completed
- [x] BoundingBoxHelper #4667
- [x] Raycaster Backface #5613  @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/CameraHelper.html
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/HemisphereLightHelper
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/SpotLightHelper @TatumCreative
- [x] extras/core/Gyroscope.html @TatumCreative
- [x] extras/core/Shape.html @TatumCreative
- [x] extras/objects/MorphBlendMesh.html @TatumCreative
- [x] objects/Bone.html @TatumCreative
- [x] materials/MeshLambertMaterial.html @TatumCreative
- [x] materials/MeshPhongMaterial.html @TatumCreative
- [x] materials/SpriteCanvasMaterial.html @TatumCreative
- [x] materials/SpriteMaterial.html @TatumCreative
- [x] Improve cross referencing @caseygrun #5405 #5477 #5415
- [x] Build dat.GUI previews of Materials @TatumCreative #5375
- [x] objects/LensFlare.html @TatumCreative
- [x] objects/LOD.html @TatumCreative
- [x] objects/MorphAnimMesh.html @TatumCreative
- [x] objects/WebGLShader.html @TatumCreative

Core
- [x] http://threejs.org/docs/#Reference/Core/BufferAttribute @caseygrun #5406
- [x] http://threejs.org/docs/#Reference/Core/BufferGeometry (attributes) @caseygrun #5406

Loaders
- [x] loaders/BufferGeometryLoader.html  @vincent #5485
- [x] loaders/Cache.html  @vincent #5485
- [x] loaders/ImageLoader.html  @vincent #5485
- [x] loaders/JSONLoader.html  @vincent #5485
- [x] loaders/Loader.html  @vincent #5485
- [x] loaders/LoadingManager.html  @vincent #5485
- [x] loaders/MaterialLoader.html  @vincent #5485
- [x] loaders/ObjectLoader.html  @vincent #5485
- [x] loaders/TextureLoader.html  @vincent #5485
- [x] loaders/XHRLoader.html  @vincent #5485

Materials
- [x] http://threejs.org/docs/#Reference/Materials/ShaderMaterial @caseygrun #5455
- [x] http://threejs.org/docs/#Reference/Materials/RawShaderMaterial @caseygrun

Extras
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/DirectionalLightHelper @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/EdgesHelper @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/FaceNormalsHelper @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/PointLightHelper @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/VertexNormalsHelper @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/VertexTangentsHelper @caseygrun 
- [x] http://threejs.org/docs/#Reference/Extras.Helpers/WireframeHelper @caseygrun 
- [x] extras/animation/AnimationMorphTarget.html @TatumCreative
- [x] extras/animation/KeyFrameAnimation.html @TatumCreative
- [x] extras/cameras/CubeCamera.html #5731  @TatumCreative
- [x] extras/core/CurvePath.html @TatumCreative
- [x] extras/core/Path.html @caseygrun
- [x] extras/ImageUtils.html @TatumCreative

Extras/Curves
- [x] http://threejs.org/docs/#Reference/Extras.Curves/ArcCurve @TatumCreative
- [x] http://threejs.org/docs/#Reference/Extras.Curves/ClosedSplineCurve3 @TatumCreative
- [x] http://threejs.org/docs/#Reference/Extras.Curves/CubicBezierCurve @TatumCreative #5491
- [x] http://threejs.org/docs/#Reference/Extras.Curves/CubicBezierCurve3 @TatumCreative #5491
- [x] http://threejs.org/docs/#Reference/Extras.Curves/EllipseCurve @TatumCreative
- [x] http://threejs.org/docs/#Reference/Extras.Curves/LineCurve @TatumCreative
- [x] http://threejs.org/docs/#Reference/Extras.Curves/LineCurve3 @TatumCreative
- [x] http://threejs.org/docs/#Reference/Extras.Curves/QuadraticBezierCurve @TatumCreative #5491
- [x] http://threejs.org/docs/#Reference/Extras.Curves/QuadraticBezierCurve3 @TatumCreative #5491
- [x] http://threejs.org/docs/#Reference/Extras.Curves/SplineCurve @TatumCreative
- [x] http://threejs.org/docs/#Reference/Extras.Curves/SplineCurve3 @TatumCreative

Extras / Geometries
- [x] http://threejs.org/docs/#Reference/Extras.Geometries/ShapeGeometry @TatumCreative #5414
- [x] http://threejs.org/docs/#Reference/Extras.Geometries/ParametricGeometry @TatumCreative #5414
- [x] http://threejs.org/docs/#Reference/Extras.Geometries/PolyhedronGeometry @TatumCreative #5414
- [x] http://threejs.org/docs/#Reference/Extras.Geometries/OctahedronGeometry @TatumCreative #5414
- [x] http://threejs.org/docs/#Reference/Extras.Geometries/DodecahedronGeometry @TatumCreative #5414
- [x] http://threejs.org/docs/#Reference/Extras.Geometries/TubeGeometry @TatumCreative #5414

Renderers
- [x] renderers/CanvasRenderer.html #5731
- [x] renderers/webgl/WebGLShader.html #5731
- [x] renderers/WebGLRenderer.html #5731
- [x] renderers/WebGLRenderTargetCube.html #5731

**Comment by caseygrun** [comment]
Okay, back on track! Helpers done in #5903 and Raycaster done in #5905.

I'll be doing the `extras/core` stuff next!

**Comment by TatumCreative** [comment]
Ok great, I'll try and hop back in here sometime soon too, although I'm going to have a new baby girl here within a month so I may be out for a couple of months. I'll at least try and keep this issue organized. We'll see.

**Comment by mrdoob** [comment]
@TatumCreative Congrats! \:D/

**Comment by zz85** [comment]
Congrats Grieg!

**Comment by TatumCreative** [comment]
Well thank you :)

**Comment by TatumCreative** [comment]
403 todos down to 214 with #6511.

**Comment by WestLangley** [comment]
@TatumCreative Of course, may thanks for your work on the docs!

If you type `renderer.info` into the console after adjusting geometry parameters in the doc demos, you will see something like this;

    > renderer.info
        geometries: 330
        programs: 2

The solution in this case is to do this:

	function updateGroupGeometry( mesh, geometry ) {
		
		mesh.children[0].geometry.dispose();
		mesh.children[1].geometry.dispose();

		mesh.children[0].geometry = geometry
		mesh.children[1].geometry = geometry.clone()

	}

**Comment by TatumCreative** [comment]
Getting sooo close with #6523

97 more todos!

**Comment by sukhwant** [comment]
Hi. Nice to see that documentation will be available. Often users have to dig into code and look for help. I too want to help in documentation making it easy for beginners. 
What all core things are left. So that I can start with those. And then we can go deep in documenting and creating small demos for them.

Few things I want to mention which can be helpful for developers -
1. Good documentation of each and every properties of any API.
2. Usage of each API.
3. Demo with each API.(if possible)

Besides I think it would be great if the examples provided have comments in them so that users can understand how its done.

Pls let me know list of things remaining.

**Comment by WestLangley** [comment]
@sukhwant If you'd like, you can identify the properties and methods of each class for which documentation is missing, and add it -- or add a stub, if you do not know what to write.

**Comment by TatumCreative** [comment]
@sukhwant I agree with @WestLangley, stubbing out the missing pages is the most immediate need for sure. This file has the template for a new page: https://github.com/mrdoob/three.js/blob/master/docs/api/Original.html

I'm currently working on documenting the bones and SkinnedMesh a bit better right now. Mainly I've been working on the things I have the most immediate need to use for myself :)

Another thing we need to do is linking all the existing examples correctly like on this page: https://github.com/mrdoob/three.js/blob/dev/docs/api/cameras/CubeCamera.html#L16-L20

**Comment by sukhwant** [comment]
OK great.
 I have got some missing things which are not in document and also some broken links in the document.
I will first start with linking examples and correcting broken links.

**Comment by hena-3** [comment]
@sukhwant I am working on improving lights docs and linking examples.

**Comment by sukhwant** [comment]
@hena-3 great. I will finish camera and send a PR, mostly by today.

**Comment by pailhead** [comment]
What does THREE.Group() do?

**Comment by mrdoob** [comment]
It's for grouping objects.

Before we used `THREE.Object3D()` for that, but `THREE.Group` hints the renderer to not look for geometries or materials.

**Comment by pailhead** [comment]
`THREE.Object3D` should not be used anymore? Only things extending from it? (Scene, Mesh, Group)?

**Comment by looeee** [comment]
@mrdoob, @gregtatum (are you still around?) 

I think this issue can be closed now - the remaining open issues are obsolete or have been completed. 

The API is now 100% documented!

Except for RectAreaLight, RectAreaLightHelper, and the various IDCounts constants... and all the things I probably missed of course. 

I do have another list of things that need to be done, such as documenting controls and a few live examples that need fixing. 
Perhaps more up to date document improvement project could be opened?
